import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Brevo API configuration
const BREVO_API_KEY = Deno.env.get("BREVO_API_KEY");
const BREVO_API_URL = "https://api.brevo.com/v3/smtp/email";
const FROM_EMAIL = Deno.env.get("FROM_EMAIL") || "noreply@yourapp.com";
const FROM_NAME = Deno.env.get("FROM_NAME") || "Task Manager";
const EXPO_PUSH_URL = "https://exp.host/--/api/v2/push/send";

// Send email via Brevo
async function sendBrevoEmail(toEmail: string, toName: string, subject: string, htmlContent: string) {
  if (!BREVO_API_KEY) {
    console.log("BREVO_API_KEY not set, skipping email send");
    return { success: false, error: "BREVO_API_KEY not configured" };
  }

  try {
    const response = await fetch(BREVO_API_URL, {
      method: "POST",
      headers: {
        "accept": "application/json",
        "api-key": BREVO_API_KEY,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        sender: {
          email: FROM_EMAIL,
          name: FROM_NAME,
        },
        to: [
          {
            email: toEmail,
            name: toName,
          },
        ],
        subject: subject,
        htmlContent: htmlContent,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error("Brevo API error:", errorData);
      return { success: false, error: errorData };
    }

    const data = await response.json();
    console.log("Email sent successfully:", data);
    return { success: true, data };
  } catch (error) {
    console.error("Failed to send email:", error);
    return { success: false, error: error.message };
  }
}

// Generate email template based on notification type
function getEmailTemplate(type: string, title: string, message: string) {
  const colors = {
    task_assigned: "#3b82f6",
    task_completed: "#22c55e",
    deadline_missed: "#ef4444",
  };

  const color = colors[type as keyof typeof colors] || "#666";

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${title}</title>
    </head>
    <body style="margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f5f5f5;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 20px;">
        <tr>
          <td align="center">
            <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
              <tr>
                <td style="padding: 30px; border-bottom: 3px solid ${color};">
                  <h1 style="margin: 0; color: #333; font-size: 24px;">${title}</h1>
                </td>
              </tr>
              <tr>
                <td style="padding: 30px;">
                  <p style="margin: 0; color: #666; font-size: 16px; line-height: 1.5;">${message}</p>
                </td>
              </tr>
              <tr>
                <td style="padding: 20px 30px; background-color: #f9f9f9; border-radius: 0 0 8px 8px;">
                  <p style="margin: 0; color: #999; font-size: 12px;">This is an automated notification from Task Manager.</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const { userId, title, message, type, taskId } = await req.json();

    // Get user email and profile
    const { data: user, error: userError } = await supabaseClient.auth.admin.getUserById(userId);
    
    if (userError || !user.user) {
      throw new Error("User not found");
    }

    // Get user profile for name and push token
    const { data: profile } = await supabaseClient
      .from("profiles")
      .select("fullname, push_token")
      .eq("id", userId)
      .single();

    const userName = profile?.fullname || user.user.email?.split("@")[0] || "User";

    // In-app notification rows are generated by DB triggers.
    // This edge function only handles external delivery channels.

    // Send email via Brevo
    const emailResult = await sendBrevoEmail(
      user.user.email!,
      userName,
      title,
      getEmailTemplate(type, title, message)
    );

    // Send push notification if a push token exists
    let pushSent = false;
    let pushError: unknown = null;
    if (profile?.push_token) {
      try {
        const pushResponse = await fetch(EXPO_PUSH_URL, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            to: profile.push_token,
            sound: "default",
            title,
            body: message,
            data: {
              type,
              taskId: taskId ?? null,
            },
          }),
        });

        if (!pushResponse.ok) {
          pushError = await pushResponse.text();
          console.error("Push send failed:", pushError);
        } else {
          pushSent = true;
        }
      } catch (err: any) {
        pushError = err?.message || err;
        console.error("Push send failed:", pushError);
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        emailSent: emailResult.success,
        emailError: emailResult.error || null,
        pushSent,
        pushError,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error: any) {
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 400,
      }
    );
  }
});
